/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package siscolaboradores;

import java.text.DecimalFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ciretran
 */
public class CltFormulario extends java.awt.Frame {
    Clt cltUm = new Clt("","","",0,0,"",0,0,0);
    

    /**
     * Creates new form CltFormulario
     */
    public CltFormulario() {
        initComponents();
        this.setLocationRelativeTo(null); // seta a localização para o centro da tela
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfCltEndereco = new javax.swing.JTextField();
        lblCltNome = new javax.swing.JLabel();
        lblCltEndereco = new javax.swing.JLabel();
        lblCltTel = new javax.swing.JLabel();
        lblCltRg = new javax.swing.JLabel();
        lblCltCpf = new javax.swing.JLabel();
        lblCltSalario = new javax.swing.JLabel();
        tfCltNome = new javax.swing.JTextField();
        tfCltRg = new javax.swing.JTextField();
        tfCltSalario = new javax.swing.JTextField();
        btnCltSalvar = new javax.swing.JButton();
        btnCltCalcPag = new javax.swing.JButton();
        btnCltSair = new javax.swing.JButton();
        lblCltHorasTrab = new javax.swing.JLabel();
        tfCltHorasTrab = new javax.swing.JTextField();
        tfCltCpf = new javax.swing.JFormattedTextField();
        tfCltTel = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(204, 204, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        tfCltEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCltEnderecoActionPerformed(evt);
            }
        });

        lblCltNome.setText("Nome");

        lblCltEndereco.setText("Endereço");

        lblCltTel.setText("Telefone");

        lblCltRg.setText("RG");

        lblCltCpf.setText("CPF");

        lblCltSalario.setText("Salário");

        tfCltNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCltNomeActionPerformed(evt);
            }
        });

        btnCltSalvar.setText("Salvar");
        btnCltSalvar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnCltSalvarFocusLost(evt);
            }
        });
        btnCltSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCltSalvarActionPerformed(evt);
            }
        });

        btnCltCalcPag.setText("Calcular Pagto");
        btnCltCalcPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCltCalcPagActionPerformed(evt);
            }
        });

        btnCltSair.setText("Voltar");
        btnCltSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCltSairActionPerformed(evt);
            }
        });

        lblCltHorasTrab.setText("Horas Trabalhadas");

        tfCltHorasTrab.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfCltHorasTrabFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCltHorasTrabFocusLost(evt);
            }
        });

        try {
            tfCltCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCltCpf.setToolTipText("");

        try {
            tfCltTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfCltNome)
            .addComponent(tfCltEndereco)
            .addComponent(tfCltRg)
            .addComponent(tfCltSalario, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(tfCltHorasTrab)
            .addComponent(tfCltCpf)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCltCpf)
                    .addComponent(lblCltSalario)
                    .addComponent(lblCltTel)
                    .addComponent(lblCltNome)
                    .addComponent(lblCltEndereco)
                    .addComponent(lblCltRg)
                    .addComponent(lblCltHorasTrab)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCltSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCltCalcPag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCltSair)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(tfCltTel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCltNome)
                .addGap(1, 1, 1)
                .addComponent(tfCltNome)
                .addGap(4, 4, 4)
                .addComponent(lblCltEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCltEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCltTel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(tfCltTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCltRg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCltRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCltCpf)
                .addGap(1, 1, 1)
                .addComponent(tfCltCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCltSalario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(tfCltSalario)
                .addGap(4, 4, 4)
                .addComponent(lblCltHorasTrab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCltHorasTrab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCltSalvar)
                    .addComponent(btnCltCalcPag)
                    .addComponent(btnCltSair)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
       System.exit(0); // Encerra o sistema
    }//GEN-LAST:event_exitForm

    private void tfCltEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCltEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCltEnderecoActionPerformed

    private void tfCltNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCltNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCltNomeActionPerformed

    private void btnCltSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCltSalvarActionPerformed
        // TODO add your handling code here:
        String nome, endereco, tel, rg, cpf, salario, horas;
        
        
//O bloco abaixo recebe o conteúdo das Text Fields e dá atributos às variáveis locais abaixo
        nome = tfCltNome.getText(); 
        endereco = tfCltEndereco.getText();
        tel = tfCltTel.getText();
        rg = tfCltRg.getText();
        cpf = tfCltCpf.getText();
        salario = tfCltSalario.getText();
        horas = tfCltHorasTrab.getText();
        
        if (nome.equals("") || endereco.equals("") || tel.equals("(  )    -    ") || rg.equals("") || cpf.equals("   .   .   -  ") || salario.equals("") || horas.equals("")){
            JOptionPane.showMessageDialog(null, "PREENCHER TODOS OS CAMPOS" ,"Erro", JOptionPane.ERROR_MESSAGE); // Caso não estejam preenchidas, retorna mensagem de ERRO.    
        }
        
        else{ 
            
            if (Integer.parseInt(horas) < 160){ // mensagem de erro caso horas trabalhadas seja abaixo de 160
                JOptionPane.showMessageDialog(null, "CLT deve ter no mínimo 160 horas trabalhadas no mês" ,"Erro", JOptionPane.ERROR_MESSAGE);
            }
            else{ // caso a verificação acima esteja ok, seta todos os dados.
                cltUm.setNome(nome);
                cltUm.setEndereco(endereco);
                cltUm.setTel(tel);
                cltUm.setRg(Integer.parseInt(rg));
                cltUm.setCpf(cpf);
                cltUm.setSalario(Double.parseDouble(salario));
                cltUm.setHoras(Integer.parseInt(horas));
                JOptionPane.showMessageDialog(null, "CLT Cadastrado");
            }
        }

//O bloco abaixo envia e seta os dados recebidos para a classe equivalente
           
    }//GEN-LAST:event_btnCltSalvarActionPerformed

    private void btnCltSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCltSairActionPerformed
        this.dispose(); // método para fechar a janela
        String opcao; // volta para a tela inicial apos sair da janela
        do{
                opcao = JOptionPane.showInputDialog("Informe o tipo de colaborador (CLT ou PJ)");
                if (opcao == null) {
                    System.exit(0);
                }
                
                opcao = opcao.toUpperCase(); // transforma em caixa alta caso a opção tenha sido digitada em caixa baixa
                
                if (opcao.equals("CLT")){
                    new CltFormulario().setVisible(true); // exibe o formulário caso a condição acima seja verdadeira
                }
                else if (opcao.equals("PJ")){
                    new PjFormulario().setVisible(true);
                }     
        } while (!opcao.equals("CLT") && ! opcao.equals("PJ"));         
       
    }//GEN-LAST:event_btnCltSairActionPerformed

    private void btnCltCalcPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCltCalcPagActionPerformed
        
        String nome = cltUm.getNome(); //  variáveis locais
        String endereco = cltUm.getEndereco();
        String tel = cltUm.getTel();
        long rg = cltUm.getRg();
        String cpf = cltUm.getCpf();
        double salario = cltUm.getSalario();
        int horas = cltUm.getHoras();     
        
        DecimalFormat df = new DecimalFormat("###,###,##0.00"); // Método de formatação para números do tipo Float
        df.setMaximumFractionDigits(2); // definido como 2 digitos após a casa decimal
        
        if (nome.equals("") || endereco.equals("") || tel.equals("(  )    -    ") || rg==0 || cpf.equals("   .   .   -  ") || salario==0 || horas==0){ // Verifica se todos os campos estão preenchidos
            JOptionPane.showMessageDialog(null, "É necessário salvar um funcionário antes de calcular o pagamento.\n Caso ja tenha digitado, clique em salvar." ,"Erro", JOptionPane.ERROR_MESSAGE);         
        }   
        
        else{ // Caso não estejam, retorna mensagem de ERRO.        
            JOptionPane.showMessageDialog(null, "Nome: " + cltUm.getNome() + 
            "\nEndereço: " + cltUm.getEndereco() + "\nTelefone: " + cltUm.getTel() + 
            "\nRG: " + cltUm.getRg() + "\nCPF: " + cltUm.getCpf() + 
            "\nSalário Bruto: R$" + df.format(salario) + 
            "\nINSS: R$-" + df.format(cltUm.calcularINSS()) +
            "\nImposto de Renda Retido na Fonte: R$-" + df.format(cltUm.calcularIRRF(salario)) +
            "\nHoras Extras: R$" + df.format(cltUm.horasExtras()) +
            "\nSalário Líquido: R$" + df.format(cltUm.salarioLiquido()));
        }
        
        
    }//GEN-LAST:event_btnCltCalcPagActionPerformed

    private void btnCltSalvarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCltSalvarFocusLost
        
    }//GEN-LAST:event_btnCltSalvarFocusLost

    private void tfCltHorasTrabFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCltHorasTrabFocusLost

        // TODO add your handling code here:
    }//GEN-LAST:event_tfCltHorasTrabFocusLost

    private void tfCltHorasTrabFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCltHorasTrabFocusGained
        
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCltHorasTrabFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CltFormulario().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCltCalcPag;
    private javax.swing.JButton btnCltSair;
    private javax.swing.JButton btnCltSalvar;
    private javax.swing.JLabel lblCltCpf;
    private javax.swing.JLabel lblCltEndereco;
    private javax.swing.JLabel lblCltHorasTrab;
    private javax.swing.JLabel lblCltNome;
    private javax.swing.JLabel lblCltRg;
    private javax.swing.JLabel lblCltSalario;
    private javax.swing.JLabel lblCltTel;
    private javax.swing.JFormattedTextField tfCltCpf;
    private javax.swing.JTextField tfCltEndereco;
    private javax.swing.JTextField tfCltHorasTrab;
    private javax.swing.JTextField tfCltNome;
    private javax.swing.JTextField tfCltRg;
    private javax.swing.JTextField tfCltSalario;
    private javax.swing.JFormattedTextField tfCltTel;
    // End of variables declaration//GEN-END:variables
}
